### ISSUE TITLE
Question neovim on conda-forge

### ISSUE THREAD

**Issue by brianmcconnel** [conda-forge/neovim-feedstock#14]
Issue:
I was wondering if anyone had considered expanding this feedstock to include the latest version of the neovim itself and not just the python client.  

I was considering doing it, but wondered if there was a reason this had not been done before digging deeper.  It would be super convenient and making set up of a development environment that much easier.

Note: In most of the package managers I seem this python client under "python-neovim" not just neovim.

**Comment by curtisalexander** [comment]
@brianmcconnel Others have requested similar.  The only reason I haven't done it to date is simply because I haven't done the effort to research how it could be done.  If you are interested in picking up, definitely feel free.

Ultimately, I think that this package probably needs to become a meta package that includes neovim as well as the python neovim client.  Then a separate package with just the python client should be created separately that mirrors the current state of this package.

**Comment by brianmcconnel** [comment]
@curtisalexander Thanks, I'll see what I can do in my spare time.

**Comment by lukelbd** [comment]
So to clarify this feedstock just provides `pynvim`? Isn't that redundant with the [existing `pynvim` feedstock](https://github.com/conda-forge/pynvim-feedstock)?

Would love to see this turn into a neovim provider. There's already a great [vim feedstock](https://github.com/conda-forge/vim-feedstock) I use to update vim on different systems.

**Comment by lukelbd** [comment]
Alternatively someone could start a separate feedstock for neovim, e.g. named `nvim`.

Looks like there are not currently any `conda-forge` feedstocks named `nvim`:

```sh
enceladus[0]:dotfiles$ mamba install nvim

Looking for: ['nvim']

conda-forge/osx-64                                          Using cache
conda-forge/noarch                                          Using cache

Pinned packages:
  - python 3.9.*


Encountered problems while solving:
  - nothing provides requested nvim
```

**Comment by wybert** [comment]
@brianmcconnel Any updates now?

**Comment by xhochy** [comment]
The editor is packaged in the `nvim` package: https://github.com/conda-forge/nvim-feedstock
